name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:v1
    volumes:
      - database_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:v1
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:v1
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html:ro
      # :ro = read only, que es lo unico que hace nginx, leer los archivos que ponga wordpress
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

networks:
   inception-network:
     driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/martalc/data/wordpress
      # es 'martalc' porque es el usuario de la MV
      # esta carpeta es la que va ligada con /var/www/html en el contenedor de nginx y el de wordpress
  database_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/martalc/data/database
