name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception-network
    restart: always

  wordpress:
    container_name: wordpress-php
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

networks:
   inception-network:
     driver: bridge


 #   environment:
 #     WORDPRESS_DB_HOST: db:3306
 #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
 #     WORDPRESS_DB_USER: ${MYSQL_USER}
 #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
