version: "3.8"

services:
  db:
    build: ./srcs/mariadb
    env_file:
      - .env
    networks:
      - wp-network

 # wordpress:
 #   build: ./wordpress
 #   env_file:
 #     - .env
 #   environment:
 #     WORDPRESS_DB_HOST: db:3306
 #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
 #     WORDPRESS_DB_USER: ${MYSQL_USER}
 #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
 #   networks:
 #     - wp-network

networks:
  wp-network:
